# Generated by Django 5.1.7 on 2025-03-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Article Name')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Article Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='About the article')),
            ],
        ),
    ]
