# Generated by Django 5.1.7 on 2025-03-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDapp', '0002_articles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='type',
            field=models.CharField(choices=[('jewellery', 'jewellery'), ('potrait', 'potrait'), ('crochet', 'crochet')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
